reactjs:
  name: testproject
  parameterPath: /service/test-build/testproject
  parameters: 
    - domain: "url domain"
  branch:
    - name: master
      environments:
        - name: dev
          region: us-west-2